### ISSUE TITLE
Extend ID limits

### ISSUE THREAD

**Issue by labpaw** [MinecraftForkage/MinecraftForkage#3] opened 2015-02-14 14:47 UTC
Ok, here we go. If you don't like this idea just close it. Numerical IDs gone in MC 1.7.10, that's means no more conflicts but the number of IDs still limited. Here: https://github.com/MinecraftForge/FML/blob/9c3013e02af1bd2f724d34a30e0b880b6e131645/src/main/java/net/minecraftforge/fml/common/registry/GameData.java#L65 The idea is to extend them or even remove all limits. Not sure if it even possible but maybe? If it only possible to extend them, 2x count should be enough. This should be done for block, biome and enchantment IDs. Not sure if it needed for items, since the limit is big enough. If it possible will it cause issues? And what kind of issues?

**Comment by labpaw** [comment] 2015-02-21 20:24
@immibis anything on this? Is something like this even possible?

**Comment by immibis** [comment] 2015-02-22 03:08
It should be possible. The most drastic change would be to the save game format, since it wouldn't be vanilla-compatible (or Forge-compatible) any more, so I suppose that needs to be a config option.

**Comment by labpaw** [comment] 2015-02-22 06:11
So, mods should be updated to Forkage to get this option to work? Or what? I guess it applies to only block IDs, yes? Biome, enchantment IDs should be compatible with vanilla, right? Because there are coremod exist which extends enchantment IDs without compatibility problems. Or maybe it's better to make some kind of module(plugin) which will extend these IDs?

**Comment by immibis** [comment] 2015-02-22 09:43
Do some testing with this build: https://dl.dropboxusercontent.com/u/2944265/mods/mcforkage/installer-1.2-MoreIDs.jar (installer link). It should allow block IDs up to 31999 (the same as items).

Also, for testing purposes, the preferred ID allocation order is reversed - mod blocks start at 4096, and items start from just after the vanilla Minecraft blocks.

This version has no config option to turn this on or off, and doesn't have a converter from normal-format worlds (so you'll need to create a new world). Those things are possible, I just haven't done them yet.

This is the [moreIDs](https://github.com/MinecraftForkage/MinecraftForkage/tree/moreIDs) branch.

**Comment by labpaw** [comment] 2015-02-22 10:45
Hmm, I can't start the game with this build. When I hit play, it downloads some files(or tries to download) and then nothing happens. No crash, no load, nothing.

Edit: Getting this in log -> http://pastebin.com/SYkF9r0L Where I can get these libs? And where I should drop them?
Edit2: Downloaded needed libs but now when I hit start, launcher just closing. Log: http://pastebin.com/MzDVpXu7

**Comment by keybounce** [comment] 2015-02-22 17:08
Ohh ... yummy ... waiting for compatibility (I'm only up to around 800 blocks, I think.)

**Comment by immibis** [comment] 2015-02-23 06:21
@Adaptivity A trivial problem - I don't know why it was working before.

Try https://dl.dropboxusercontent.com/u/2944265/mods/mcforkage/installer-1.2-MoreIDs-fixed.jar

**Comment by labpaw** [comment] 2015-02-23 06:28
Still getting this -> http://pastebin.com/MzDVpXu7 I've quite a lot of mods in pack(about 190) that seems it conflicts with some mod.

**Comment by labpaw** [comment] 2015-02-23 06:46
Issue 1: found one incompatible mod: https://github.com/Mine-and-blade-admin/Battlegear2
Got this crash: http://pastebin.com/jbLutPt6
Issue 2: http://i.imgur.com/hWmb6WW.jpg - update all numbers to Forge 10.13.2.1307

**Comment by immibis** [comment] 2015-02-23 07:39
Try with this version of AppleCore: https://dl.dropboxusercontent.com/u/2944265/mods/mcforkage/ModPort-AppleCore.jar

You may have to test without Mine and Blade for now.

**Comment by labpaw** [comment] 2015-02-23 07:59
Can you also check issue 2 in the same post? That seems that coFH mods requires Forge 1291 but the Forge numbers in Forkage are outdated.

**Comment by immibis** [comment] 2015-02-23 08:22
https://dl.dropboxusercontent.com/u/2944265/mods/mcforkage/installer-1.2-MoreIDs-fixed2.jar <- with the Forge version number set to 1291 (the actual Forge changes should have already been included)

**Comment by labpaw** [comment] 2015-02-23 08:53
Loaded in with 195 mods. Now getting crash during world creation: http://pastebin.com/DVeGGTLR
Removing underground biomes solves the problem and I can enter the world but then I'm getting another crash: http://pastebin.com/sHavtj89 Removing both and I'm in the world but all modded blocks have no breaking particles. I'll try to regenerate the config files, this might help.

**Comment by labpaw** [comment] 2015-02-23 09:17
http://pastebin.com/ZTXHNGcs another crash. Something about food stuff. And yes, I'm using your modded AppleCore. Also, breaking particles not working on blocks from mods, dunno why. They just drops when you breaks them, without particles.

**Comment by immibis** [comment] 2015-02-23 19:02
Last one is a bug in the Apple Core port, fixed version: https://dl.dropboxusercontent.com/u/2944265/mods/mcforkage/ModPort-AppleCore-fixed.jar

**Comment by immibis** [comment] 2015-02-24 05:46
It's not surprising that Fastcraft breaks when details that should be irrelevant are changed - that's just the nature of Fastcraft, it makes weird changes to things.

Block digging particles work for me, but the particles when the block actually disappears are the ones from the corresponding ID less than 4096. Since most of those IDs aren't block that would explain why most blocks have no particles.

**Comment by immibis** [comment] 2015-02-24 07:38
https://dl.dropboxusercontent.com/u/2944265/mods/mcforkage/installer-1.2-MoreIDs-2.jar - fixed particles

**Comment by labpaw** [comment] 2015-02-24 12:15
So, is it possible to make some kind of compat plugins for incompatible mods like Fastcraft?

**Comment by PrincessOfEvil** [comment] 2015-02-24 12:16
Most likely not. The block id change is massive.

2015-02-24 18:15 GMT+06:00 Anton notifications@github.com:

**Comment by labpaw** [comment] 2015-02-24 16:13
So, current issues are:
1) Mine & Blade Battlegear 2 not working. http://pastebin.com/jbLutPt6
2) Fastcraft not working. http://pastebin.com/sHavtj89 (And never will?)
3) Underground Biomes Constructs not working. http://pastebin.com/DVeGGTLR (It tries to change blocks with id higher than 4096 but can't)
4) Really minor issue: I dunno why but here -> http://i.imgur.com/CiKMI7h.jpg displays HEE mod name but why? In just Forge it doesn't displays. And this only happens with HEE.
5) Got rash during testing: http://pastebin.com/4m10WGz4 (Getting this while typing something in NEI search)

**Comment by immibis** [comment] 2015-02-28 11:44
1) Not specifically caused by expanded IDs, but caused by the different install process in Minecraft Forkage (to simplify things, obfuscated names _no longer exist_, which breaks a small number of coremods).

2) is caused by expanded IDs, and will require an update to FastCraft.

3) is caused by expanded IDs, and Minecraft Forkage now patches UBC to fix this.

4) is caused by the lack of obfuscated names making HEE think it's in a development environment, and Minecraft Forkage now patches it to fix this.

5) is a bug in Minecraft Forkage, caused by expanded IDs, which is now fixed.

Here's an update with 3, 4 and 5 fixed: https://dl.dropboxusercontent.com/u/2944265/mods/mcforkage/installer-1.2-MoreIDs-3.jar

For 1 I'll probably have to update the mod separately. For 2, nothing in FastCraft is changeable unless I can get Player to do it, so your only option right now is to not use FastCraft.

**Comment by labpaw** [comment] 2015-02-28 17:46
For 1 maybe you can make a PR to it since the mod is open source? For FastCraft, I guess player can change it if you request it.

**Comment by keybounce** [comment] 2015-02-28 17:56
> 1) Not specifically caused by expanded IDs, but caused by the different install process in Minecraft Forkage (to simplify things, obfuscated names no longer exist, which breaks a small number of coremods).

Is this why CCC breaks in Forkage? 
Do you have a guide for people who want to port coremods to work with both systems? I thought the whole point of coremods was to transform the base classes, which required knowing their obfuscated names.

**Comment by labpaw** [comment] 2015-02-28 18:34
Also, @immibis can you extend biome or enchantment IDs for the next build?

**Comment by immibis** [comment] 2015-03-01 00:39
@keybounce Yes, although CCC doesn't use obfuscated names, it uses SRG names (which most coremods _should_, because it makes their lives easier).

To make a coremod compatible: add @SortingIndex(1500) (or any number over 1000) to your IFMLLoadingPlugin class. Then use SRG names instead of obfuscated names. It even works in actual Forge!

**Comment by immibis** [comment] 2015-03-01 07:08
Try this version of Battlegear 2: https://dl.dropboxusercontent.com/u/2944265/mods/mcforkage/ModPort-MABBattleGear2.jar

**Comment by labpaw** [comment] 2015-03-01 07:27
Got two crashes on startup with this version of Battlegear 2: 1) http://pastebin.com/AAnpfDTt 2) http://pastebin.com/Y4j917d9

**Comment by immibis** [comment] 2015-03-01 07:44
@Adaptivity Are boneanas a thing added by BG2?

**Comment by labpaw** [comment] 2015-03-01 08:28
Nope, it's TiC stuff. But it's doesn't crash without BG2.
Another crash: http://pastebin.com/1QV4QAvc

**Comment by immibis** [comment] 2015-03-01 22:21
@Adaptivity Can't reproduce the first crash - I can use TCon weapons with BG2.

For the second one, do you have any mods installed that affect food (apart from adding new foods, and apart from Apple Core)?

**Comment by labpaw** [comment] 2015-03-02 10:33
I'll look into Tcon crash later.
For the second, I have https://github.com/progwml6/HungerOverhaul and https://github.com/squeek502/SpiceOfLife in my pack.

**Comment by labpaw** [comment] 2015-03-13 15:03
Any news on the second crash? Still have no time to check TCon crash but I'll try to do it on this weekend. Also, since you made a PR for BG2, you can make it for AppleCore too -> https://github.com/squeek502/AppleCore

**Comment by labpaw** [comment] 2015-05-22 17:08
@immibis are you alive? Do you plan to continue developing this project? Any news will be appreciated.

**Comment by Solarstrike** [comment] 2015-05-23 04:12
@Adaptivity That's why I question this project's future as well.

**Comment by Solarstrike** [comment] 2015-06-23 01:37
Hello?
~one month later

**Comment by Solarstrike** [comment] 2015-06-26 05:33
Hey @Adaptivity, can you continue this?

**Comment by labpaw** [comment] 2015-06-26 06:26
I can't. I'm just a player, not coder.

**Comment by Solarstrike** [comment] 2015-06-26 06:29
Arrrgh.
He hasn't been that active recently, his last two activities were a over a month apart.

**Comment by labpaw** [comment] 2015-06-28 09:10
@Solarstrike Just to let you know: @fewizz started on coremod which should extend block ids. No promises though. There are currently issue on serverside that some chunks not loading. Will see if he can do something. The mod will be released on curseforge when (if) it's ready. If you still interested in it I can inform you when test version is ready. This should not take much time if the server bug will be fixed.

Update: bug is fixed. Coremod is in progress.

**Comment by Solarstrike** [comment] 2015-06-29 18:33
Sure, @Adaptivity

**Comment by Solarstrike** [comment] 2015-07-01 23:09
Any updates yet?

**Comment by labpaw** [comment] 2015-07-02 05:54
Almost ready. @fewizz probably will have something on this week.

**Comment by Solarstrike** [comment] 2015-07-04 05:05
Two more days

**Comment by labpaw** [comment] 2015-07-04 11:10
https://github.com/fewizz/NotEnoughIDs/releases/tag/1.0.0
Go get it while it's hot. Don't forget to check README.md and remember this still need some testing.
The forum post will come up later today or tomorrow.

**Closed as completed** 2015-10-18 15:13 UTC
